### ISSUE TITLE
Melhor detalhamento do projeto

### ISSUE THREAD

**Issue by tomasbarcellos** [recognitium/pof2008reptab2.1.1#1]
Seria bom explicar no README.md a ordem dos scripts e como se relacionam. Assim é mais fácil entender o projeto.

**Comment by rodrigoesborges** [comment]
Melhorei um pouco a descrição do projeto com este commit
https://github.com/recognitium/pof2008reptab2.1.1/commit/17217db2ff53a3670ffb37e353d0ba8102ab39df
